import type { Stop } from "@/types/stop";

export const mockedStops: Stop[] = [
  {
    code: "SZY",
    name: "Szymanowskiego",
    lat: 52.403,
    lon: 16.928,
    id: 0,
    zone_id: "SZY",
  },
  {
    code: "KUR",
    name: "Kurpińskiego",
    lat: 52.405,
    lon: 16.93,
    id: 1,
    zone_id: "KUR",
  },
  {
    code: "PP",
    name: "Poznań Plaza",
    lat: 52.407,
    lon: 16.935,
    id: 2,
    zone_id: "PP",
  },
  {
    code: "AS",
    name: "Aleje Solidarności",
    lat: 52.41,
    lon: 16.94,
    id: 3,
    zone_id: "AS",
  },
  {
    code: "SŁ",
    name: "Słowiańska",
    lat: 52.412,
    lon: 16.945,
    id: 4,
    zone_id: "SŁ",
  },
  {
    code: "MT",
    name: "Most Teatralny",
    lat: 52.415,
    lon: 16.95,
    id: 5,
    zone_id: "MT",
  },
  {
    code: "MT",
    name: "Most Teatralny",
    lat: 52.415,
    lon: 16.95,
    id: 6,
    zone_id: "MT",
  },
  {
    code: "MT",
    name: "Most Teatralny",
    lat: 52.415,
    lon: 16.95,
    id: 7,
    zone_id: "MT",
  },
  {
    code: "MT",
    name: "Most Teatralny",
    lat: 52.415,
    lon: 16.95,
    id: 8,
    zone_id: "MT",
  },
  {
    code: "MT",
    name: "Most Teatralny",
    lat: 52.415,
    lon: 16.95,
    id: 9,
    zone_id: "MT",
  },
  {
    code: "MT",
    name: "Most Teatralny",
    lat: 52.415,
    lon: 16.95,
    id: 10,
    zone_id: "MT",
  },
];
